Q1="SELECT COUNT(name) from Movie where year=2002 and name LIKE 'Ha%' and rank>2;"
Q2="SELECT MAX(rank) from Movie where name LIKE 'Autom%' and year in (1983,1994);"
Q3="SELECT COUNT(id) from actor where gender='M' and (fname LIKE '%ei' or lname LIKE 'ei%');"
Q4="SELECT AVG(rank) as average_rank_of_movies from Movie where year in(1993,1995,2000) and rank>=4.2;"
Q5="SELECT SUM(rank) from Movie where (name LIKE '%Hary%' and year BETWEEN 1981 and 1984 and rank<9);"
Q6="SELECT year from Movie where rank=5 limit 1;"
Q7="SELECT COUNT(gender='F') FROM Actor WHERE gender='F' or fname=lname;"
Q8="SELECT DISTINCT fname from Actor where lname LIKE '%ei' order by Fname ASC limit 100;"
Q9="SELECT id,name as movie_title,year from Movie where year in(2001,2002,2005,2006) LIMIT 25 OFFSET 10;"
Q10="SELECT DISTINCT lname from Director where fname in('Yeud','Wolf','Vicky') order by lname ASC LIMIT 5;"