Q1="SELECT *from Movie order by rank desc limit 10;"
Q2="SELECT *from Movie order by rank desc limit 10 offset 10;"
Q3="SELECT name from Movie where year>2004;"
Q4="SELECT name from Movie where rank<1.1;"
Q5="SELECT *from Movie where year IN(2004,2005,2006);"
Q6="SELECT name,year from Movie where name LIKE 'Harry%';"
Q7="SELECT *from Actor where fname='Christin' and lname<>'Watson';"
Q8="SELECT *from Actor where fname='Woody' and lname='Watson';"
Q9="SELECT name from Movie where year=1990 and rank=5;"
Q10="SELECT *from Actor where fname='Christin' and lname='Watson';"
Q11="SELECT name from Movie where year BETWEEN 2003 and 2005;"
Q12="SELECT DISTINCT year from Movie order by year ASC;"
Q13="SELECT *from Actor where (fname='Christin' or lname='Watson') and gender='M' order by fname ASC limit 10;"