Q1="SELECT COUNT(name) from Movie where year=1991;"
Q2="SELECT MIN(rank) from Movie;"
Q3="SELECT MAX(rank) from Movie where year=2000;"
Q4="SELECT AVG(rank) from Movie where year=2000;"
Q5="SELECT COUNT(DISTINCT year) from Movie;"
Q6="SELECT MIN(year),MAX(year) from Movie;"